# Site settings
title: High Life NFTs
email: your-email@domain.com
url: https://jumpnet.enjinx.io/eth/project/8e1b3ef1-4176-43a2-aadc-bdebffcf1090/marketplace
description: "Nostalgic characters of the past combined with a lifestyle of the present. Owners of these NFTs will be included in special giveaways, free airdrops from our second collection + more to come."
keywords: "High Life, NFT, Enjin, Efinity, Sketchbook, $ketchbook, Baby Muva"
skills: "Hifh Life - Sketchbook - Baby Muva"
meta_author: Test Subject 1203

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: High Life NFTs
  location: D.C.
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/HighLifeNFTs
  - title: Instagram
    url: https://www.instagram.com/highlifenfts/
  - title: 
    url: 
  - title: 
    url: 
  - title: 
    url: 

# Postal address (add as many lines as necessary)
address:
  - line: The Nations Capital
  - line: Washington D.C.

# Credits content
credits: 'Cornelius, Quadre">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
